#version: '3.8'
services:
  servidorweb:
    build: servidorweb
    ports:
      - 8000:8000
  bancodedados:
    image: mysql
    ports:
      - 3306:3306
    #volumes:
    #  - servidorweb/www:/www
  redis:
    image: redis
    ports:
      - 6379:6379