/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

public class App { 
    public static void main(String[] args) { 

        System.out.println("\u2591\u2592\u2592 Iniciando servidor \u2592\u2592\u2591");
        
 
       int porta = 1234;
        try (ServerSocket servidor = new ServerSocket(porta)) {
            // Esperando cliente por tempo indeterminado
            while (true) {
                Socket cliente = servidor.accept();
                Thread atendimento = new Thread(new AtenderCliente(cliente));
                atendimento.start();
            }
 

        } catch (IOException e) {
            System.err.println("Erro na thread: " + e.getMessage());
        }

        }
        
}

