/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.Scanner;

public class App { 

    public static void main(String[] args) { 
        System.out.println("..:: Iniciando cliente ::..");

        String ipServidor = "localhost";
        int portaServidor = 1234;

        try (Socket conexao = new Socket(ipServidor, portaServidor)) {
            System.out.println("Cliente conectado");

            
            // Estabelecimento dos fluxos de entrada e saída
            BufferedReader entrada = new BufferedReader(
                new InputStreamReader(conexao.getInputStream(), "UTF-8"));

            DataOutputStream saida = new DataOutputStream(conexao.getOutputStream());
            
            String mensagem = "Oi, sou o cliente\\n";
            //saida.writeBytes(mensagem);

            Scanner teclado = new Scanner(System.in);

            while(!mensagem.equals("sair")) {
                mensagem = teclado.nextLine();

                saida.writeBytes(mensagem+"\n");
                String recebido = entrada.readLine();
                System.out.println("Servidor > " + recebido);

            }

            saida.flush(); 


        } catch (IOException e) {
            System.err.println("Erro ao inciar o cliente: " + e.getMessage());
        } 
    }
}
